# Generated by Django 4.2 on 2026-02-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cases/'),
        ),
        migrations.AddField(
            model_name='tip',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='tips/'),
        ),
    ]
